# Generated by Django 4.2.5 on 2023-09-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cementera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre producto generico"
                    ),
                ),
                (
                    "linea",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Suma de MontoLineaAdjudicada",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Suma de CantidadAdjudicada",
                    ),
                ),
                (
                    "cuenta",
                    models.IntegerField(verbose_name="Cuenta de MontoLineaAdjudicada"),
                ),
                (
                    "codigo_fecha",
                    models.CharField(max_length=6, verbose_name="mes-año"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actuialización"
                    ),
                ),
            ],
        ),
    ]
