# Generated by Django 4.2.5 on 2023-09-19 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cementera",
            unique_together={("nombre", "codigo_fecha")},
        ),
    ]
